// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: models.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XiaoyaStore.Model {

  /// <summary>Holder for reflection information generated from models.proto</summary>
  public static partial class ModelsReflection {

    #region Descriptor
    /// <summary>File descriptor for models.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModelsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxtb2RlbHMucHJvdG8SEVhpYW95YVN0b3JlLk1vZGVsIpgBCg9VcmxGcm9u",
            "dGllckl0ZW0SCwoDdXJsGAEgASgJEhQKDHBsYW5uZWRfdGltZRgCIAEoBBIQ",
            "Cghwcmlvcml0eRgDIAEoBBIUCgxmYWlsZWRfdGltZXMYBCABKA0SEgoKdXJs",
            "ZmlsZV9pZBgFIAEoBBISCgp1cGRhdGVkX2F0GAYgASgEEhIKCmNyZWF0ZWRf",
            "YXQYByABKAQicQoLUG9zdGluZ0xpc3QSDAoEd29yZBgBIAEoCRIWCg53b3Jk",
            "X2ZyZXF1ZW5jeRgCIAEoBBIaChJkb2N1bWVudF9mcmVxdWVuY3kYAyABKAQS",
            "EAoIcG9zdGluZ3MYBCADKAQSDgoGaXNfYWRkGAUgASgIIiwKCEluZGV4S2V5",
            "EhIKCnVybGZpbGVfaWQYASABKAQSDAoEd29yZBgCIAEoCSLXAQoFSW5kZXgS",
            "EAoIaW5kZXhfaWQYASABKAQSKAoDa2V5GAIgASgLMhsuWGlhb3lhU3RvcmUu",
            "TW9kZWwuSW5kZXhLZXkSFgoOd29yZF9mcmVxdWVuY3kYAyABKA0SDgoGd2Vp",
            "Z2h0GAQgASgBEhsKE29jY3VyZW5jZXNfaW5fdGl0bGUYBSABKA0SGwoTb2Nj",
            "dXJlbmNlc19pbl9saW5rcxgGIAEoDRIdChVvY2N1cmVuY2VzX2luX2hlYWRl",
            "cnMYByABKA0SEQoJcG9zaXRpb25zGAggAygNIvwCCgdVcmxGaWxlEhIKCnVy",
            "bGZpbGVfaWQYASABKAQSCwoDdXJsGAIgASgJEg0KBXRpdGxlGAMgASgJEhEK",
            "CWZpbGVfcGF0aBgEIAEoCRIRCglmaWxlX2hhc2gYBSABKAkSDwoHY29udGVu",
            "dBgGIAEoCRIUCgx0ZXh0X2NvbnRlbnQYByABKAkSDwoHY2hhcnNldBgIIAEo",
            "CRIRCgltaW1lX3R5cGUYCSABKAkSEQoJcGFnZV9yYW5rGAogASgBEhUKDWlu",
            "X2xpbmtfY291bnQYCyABKA0SHAoUaW5fbGlua190b3RhbF9sZW5ndGgYDCAB",
            "KA0SFAoMaGVhZGVyX2NvdW50GA0gASgNEhsKE2hlYWRlcl90b3RhbF9sZW5n",
            "dGgYDiABKA0SFAoMcHVibGlzaF9kYXRlGA8gASgEEhcKD3VwZGF0ZV9pbnRl",
            "cnZhbBgQIAEoBBISCgp1cGRhdGVkX2F0GBEgASgEEhIKCmNyZWF0ZWRfYXQY",
            "EiABKAQiRgoETGluaxIPCgdsaW5rX2lkGAEgASgEEhIKCnVybGZpbGVfaWQY",
            "AiABKAQSCwoDdXJsGAMgASgJEgwKBHRleHQYBCABKAkiJQoGSWRMaXN0EgsK",
            "A2lkcxgBIAMoBBIOCgZpc19hZGQYAiABKAhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::XiaoyaStore.Model.UrlFrontierItem), global::XiaoyaStore.Model.UrlFrontierItem.Parser, new[]{ "Url", "PlannedTime", "Priority", "FailedTimes", "UrlfileId", "UpdatedAt", "CreatedAt" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XiaoyaStore.Model.PostingList), global::XiaoyaStore.Model.PostingList.Parser, new[]{ "Word", "WordFrequency", "DocumentFrequency", "Postings", "IsAdd" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XiaoyaStore.Model.IndexKey), global::XiaoyaStore.Model.IndexKey.Parser, new[]{ "UrlfileId", "Word" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XiaoyaStore.Model.Index), global::XiaoyaStore.Model.Index.Parser, new[]{ "IndexId", "Key", "WordFrequency", "Weight", "OccurencesInTitle", "OccurencesInLinks", "OccurencesInHeaders", "Positions" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XiaoyaStore.Model.UrlFile), global::XiaoyaStore.Model.UrlFile.Parser, new[]{ "UrlfileId", "Url", "Title", "FilePath", "FileHash", "Content", "TextContent", "Charset", "MimeType", "PageRank", "InLinkCount", "InLinkTotalLength", "HeaderCount", "HeaderTotalLength", "PublishDate", "UpdateInterval", "UpdatedAt", "CreatedAt" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XiaoyaStore.Model.Link), global::XiaoyaStore.Model.Link.Parser, new[]{ "LinkId", "UrlfileId", "Url", "Text" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XiaoyaStore.Model.IdList), global::XiaoyaStore.Model.IdList.Parser, new[]{ "Ids", "IsAdd" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UrlFrontierItem : pb::IMessage<UrlFrontierItem> {
    private static readonly pb::MessageParser<UrlFrontierItem> _parser = new pb::MessageParser<UrlFrontierItem>(() => new UrlFrontierItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UrlFrontierItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XiaoyaStore.Model.ModelsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UrlFrontierItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UrlFrontierItem(UrlFrontierItem other) : this() {
      url_ = other.url_;
      plannedTime_ = other.plannedTime_;
      priority_ = other.priority_;
      failedTimes_ = other.failedTimes_;
      urlfileId_ = other.urlfileId_;
      updatedAt_ = other.updatedAt_;
      createdAt_ = other.createdAt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UrlFrontierItem Clone() {
      return new UrlFrontierItem(this);
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 1;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "planned_time" field.</summary>
    public const int PlannedTimeFieldNumber = 2;
    private ulong plannedTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong PlannedTime {
      get { return plannedTime_; }
      set {
        plannedTime_ = value;
      }
    }

    /// <summary>Field number for the "priority" field.</summary>
    public const int PriorityFieldNumber = 3;
    private ulong priority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Priority {
      get { return priority_; }
      set {
        priority_ = value;
      }
    }

    /// <summary>Field number for the "failed_times" field.</summary>
    public const int FailedTimesFieldNumber = 4;
    private uint failedTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint FailedTimes {
      get { return failedTimes_; }
      set {
        failedTimes_ = value;
      }
    }

    /// <summary>Field number for the "urlfile_id" field.</summary>
    public const int UrlfileIdFieldNumber = 5;
    private ulong urlfileId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UrlfileId {
      get { return urlfileId_; }
      set {
        urlfileId_ = value;
      }
    }

    /// <summary>Field number for the "updated_at" field.</summary>
    public const int UpdatedAtFieldNumber = 6;
    private ulong updatedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UpdatedAt {
      get { return updatedAt_; }
      set {
        updatedAt_ = value;
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 7;
    private ulong createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UrlFrontierItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UrlFrontierItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Url != other.Url) return false;
      if (PlannedTime != other.PlannedTime) return false;
      if (Priority != other.Priority) return false;
      if (FailedTimes != other.FailedTimes) return false;
      if (UrlfileId != other.UrlfileId) return false;
      if (UpdatedAt != other.UpdatedAt) return false;
      if (CreatedAt != other.CreatedAt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (PlannedTime != 0UL) hash ^= PlannedTime.GetHashCode();
      if (Priority != 0UL) hash ^= Priority.GetHashCode();
      if (FailedTimes != 0) hash ^= FailedTimes.GetHashCode();
      if (UrlfileId != 0UL) hash ^= UrlfileId.GetHashCode();
      if (UpdatedAt != 0UL) hash ^= UpdatedAt.GetHashCode();
      if (CreatedAt != 0UL) hash ^= CreatedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Url.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (PlannedTime != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PlannedTime);
      }
      if (Priority != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Priority);
      }
      if (FailedTimes != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(FailedTimes);
      }
      if (UrlfileId != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(UrlfileId);
      }
      if (UpdatedAt != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(UpdatedAt);
      }
      if (CreatedAt != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(CreatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (PlannedTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PlannedTime);
      }
      if (Priority != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Priority);
      }
      if (FailedTimes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FailedTimes);
      }
      if (UrlfileId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UrlfileId);
      }
      if (UpdatedAt != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UpdatedAt);
      }
      if (CreatedAt != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CreatedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UrlFrontierItem other) {
      if (other == null) {
        return;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.PlannedTime != 0UL) {
        PlannedTime = other.PlannedTime;
      }
      if (other.Priority != 0UL) {
        Priority = other.Priority;
      }
      if (other.FailedTimes != 0) {
        FailedTimes = other.FailedTimes;
      }
      if (other.UrlfileId != 0UL) {
        UrlfileId = other.UrlfileId;
      }
      if (other.UpdatedAt != 0UL) {
        UpdatedAt = other.UpdatedAt;
      }
      if (other.CreatedAt != 0UL) {
        CreatedAt = other.CreatedAt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 16: {
            PlannedTime = input.ReadUInt64();
            break;
          }
          case 24: {
            Priority = input.ReadUInt64();
            break;
          }
          case 32: {
            FailedTimes = input.ReadUInt32();
            break;
          }
          case 40: {
            UrlfileId = input.ReadUInt64();
            break;
          }
          case 48: {
            UpdatedAt = input.ReadUInt64();
            break;
          }
          case 56: {
            CreatedAt = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostingList : pb::IMessage<PostingList> {
    private static readonly pb::MessageParser<PostingList> _parser = new pb::MessageParser<PostingList>(() => new PostingList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostingList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XiaoyaStore.Model.ModelsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostingList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostingList(PostingList other) : this() {
      word_ = other.word_;
      wordFrequency_ = other.wordFrequency_;
      documentFrequency_ = other.documentFrequency_;
      postings_ = other.postings_.Clone();
      isAdd_ = other.isAdd_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostingList Clone() {
      return new PostingList(this);
    }

    /// <summary>Field number for the "word" field.</summary>
    public const int WordFieldNumber = 1;
    private string word_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Word {
      get { return word_; }
      set {
        word_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "word_frequency" field.</summary>
    public const int WordFrequencyFieldNumber = 2;
    private ulong wordFrequency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong WordFrequency {
      get { return wordFrequency_; }
      set {
        wordFrequency_ = value;
      }
    }

    /// <summary>Field number for the "document_frequency" field.</summary>
    public const int DocumentFrequencyFieldNumber = 3;
    private ulong documentFrequency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong DocumentFrequency {
      get { return documentFrequency_; }
      set {
        documentFrequency_ = value;
      }
    }

    /// <summary>Field number for the "postings" field.</summary>
    public const int PostingsFieldNumber = 4;
    private static readonly pb::FieldCodec<ulong> _repeated_postings_codec
        = pb::FieldCodec.ForUInt64(34);
    private readonly pbc::RepeatedField<ulong> postings_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> Postings {
      get { return postings_; }
    }

    /// <summary>Field number for the "is_add" field.</summary>
    public const int IsAddFieldNumber = 5;
    private bool isAdd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsAdd {
      get { return isAdd_; }
      set {
        isAdd_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostingList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostingList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Word != other.Word) return false;
      if (WordFrequency != other.WordFrequency) return false;
      if (DocumentFrequency != other.DocumentFrequency) return false;
      if(!postings_.Equals(other.postings_)) return false;
      if (IsAdd != other.IsAdd) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Word.Length != 0) hash ^= Word.GetHashCode();
      if (WordFrequency != 0UL) hash ^= WordFrequency.GetHashCode();
      if (DocumentFrequency != 0UL) hash ^= DocumentFrequency.GetHashCode();
      hash ^= postings_.GetHashCode();
      if (IsAdd != false) hash ^= IsAdd.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Word.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Word);
      }
      if (WordFrequency != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(WordFrequency);
      }
      if (DocumentFrequency != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(DocumentFrequency);
      }
      postings_.WriteTo(output, _repeated_postings_codec);
      if (IsAdd != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsAdd);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Word.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Word);
      }
      if (WordFrequency != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(WordFrequency);
      }
      if (DocumentFrequency != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(DocumentFrequency);
      }
      size += postings_.CalculateSize(_repeated_postings_codec);
      if (IsAdd != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostingList other) {
      if (other == null) {
        return;
      }
      if (other.Word.Length != 0) {
        Word = other.Word;
      }
      if (other.WordFrequency != 0UL) {
        WordFrequency = other.WordFrequency;
      }
      if (other.DocumentFrequency != 0UL) {
        DocumentFrequency = other.DocumentFrequency;
      }
      postings_.Add(other.postings_);
      if (other.IsAdd != false) {
        IsAdd = other.IsAdd;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Word = input.ReadString();
            break;
          }
          case 16: {
            WordFrequency = input.ReadUInt64();
            break;
          }
          case 24: {
            DocumentFrequency = input.ReadUInt64();
            break;
          }
          case 34:
          case 32: {
            postings_.AddEntriesFrom(input, _repeated_postings_codec);
            break;
          }
          case 40: {
            IsAdd = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class IndexKey : pb::IMessage<IndexKey> {
    private static readonly pb::MessageParser<IndexKey> _parser = new pb::MessageParser<IndexKey>(() => new IndexKey());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IndexKey> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XiaoyaStore.Model.ModelsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IndexKey() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IndexKey(IndexKey other) : this() {
      urlfileId_ = other.urlfileId_;
      word_ = other.word_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IndexKey Clone() {
      return new IndexKey(this);
    }

    /// <summary>Field number for the "urlfile_id" field.</summary>
    public const int UrlfileIdFieldNumber = 1;
    private ulong urlfileId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UrlfileId {
      get { return urlfileId_; }
      set {
        urlfileId_ = value;
      }
    }

    /// <summary>Field number for the "word" field.</summary>
    public const int WordFieldNumber = 2;
    private string word_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Word {
      get { return word_; }
      set {
        word_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IndexKey);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IndexKey other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UrlfileId != other.UrlfileId) return false;
      if (Word != other.Word) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UrlfileId != 0UL) hash ^= UrlfileId.GetHashCode();
      if (Word.Length != 0) hash ^= Word.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UrlfileId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(UrlfileId);
      }
      if (Word.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Word);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UrlfileId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UrlfileId);
      }
      if (Word.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Word);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IndexKey other) {
      if (other == null) {
        return;
      }
      if (other.UrlfileId != 0UL) {
        UrlfileId = other.UrlfileId;
      }
      if (other.Word.Length != 0) {
        Word = other.Word;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UrlfileId = input.ReadUInt64();
            break;
          }
          case 18: {
            Word = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Index : pb::IMessage<Index> {
    private static readonly pb::MessageParser<Index> _parser = new pb::MessageParser<Index>(() => new Index());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Index> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XiaoyaStore.Model.ModelsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Index() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Index(Index other) : this() {
      indexId_ = other.indexId_;
      Key = other.key_ != null ? other.Key.Clone() : null;
      wordFrequency_ = other.wordFrequency_;
      weight_ = other.weight_;
      occurencesInTitle_ = other.occurencesInTitle_;
      occurencesInLinks_ = other.occurencesInLinks_;
      occurencesInHeaders_ = other.occurencesInHeaders_;
      positions_ = other.positions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Index Clone() {
      return new Index(this);
    }

    /// <summary>Field number for the "index_id" field.</summary>
    public const int IndexIdFieldNumber = 1;
    private ulong indexId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong IndexId {
      get { return indexId_; }
      set {
        indexId_ = value;
      }
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 2;
    private global::XiaoyaStore.Model.IndexKey key_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::XiaoyaStore.Model.IndexKey Key {
      get { return key_; }
      set {
        key_ = value;
      }
    }

    /// <summary>Field number for the "word_frequency" field.</summary>
    public const int WordFrequencyFieldNumber = 3;
    private uint wordFrequency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint WordFrequency {
      get { return wordFrequency_; }
      set {
        wordFrequency_ = value;
      }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 4;
    private double weight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Weight {
      get { return weight_; }
      set {
        weight_ = value;
      }
    }

    /// <summary>Field number for the "occurences_in_title" field.</summary>
    public const int OccurencesInTitleFieldNumber = 5;
    private uint occurencesInTitle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint OccurencesInTitle {
      get { return occurencesInTitle_; }
      set {
        occurencesInTitle_ = value;
      }
    }

    /// <summary>Field number for the "occurences_in_links" field.</summary>
    public const int OccurencesInLinksFieldNumber = 6;
    private uint occurencesInLinks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint OccurencesInLinks {
      get { return occurencesInLinks_; }
      set {
        occurencesInLinks_ = value;
      }
    }

    /// <summary>Field number for the "occurences_in_headers" field.</summary>
    public const int OccurencesInHeadersFieldNumber = 7;
    private uint occurencesInHeaders_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint OccurencesInHeaders {
      get { return occurencesInHeaders_; }
      set {
        occurencesInHeaders_ = value;
      }
    }

    /// <summary>Field number for the "positions" field.</summary>
    public const int PositionsFieldNumber = 8;
    private static readonly pb::FieldCodec<uint> _repeated_positions_codec
        = pb::FieldCodec.ForUInt32(66);
    private readonly pbc::RepeatedField<uint> positions_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> Positions {
      get { return positions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Index);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Index other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IndexId != other.IndexId) return false;
      if (!object.Equals(Key, other.Key)) return false;
      if (WordFrequency != other.WordFrequency) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Weight, other.Weight)) return false;
      if (OccurencesInTitle != other.OccurencesInTitle) return false;
      if (OccurencesInLinks != other.OccurencesInLinks) return false;
      if (OccurencesInHeaders != other.OccurencesInHeaders) return false;
      if(!positions_.Equals(other.positions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IndexId != 0UL) hash ^= IndexId.GetHashCode();
      if (key_ != null) hash ^= Key.GetHashCode();
      if (WordFrequency != 0) hash ^= WordFrequency.GetHashCode();
      if (Weight != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Weight);
      if (OccurencesInTitle != 0) hash ^= OccurencesInTitle.GetHashCode();
      if (OccurencesInLinks != 0) hash ^= OccurencesInLinks.GetHashCode();
      if (OccurencesInHeaders != 0) hash ^= OccurencesInHeaders.GetHashCode();
      hash ^= positions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IndexId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(IndexId);
      }
      if (key_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Key);
      }
      if (WordFrequency != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(WordFrequency);
      }
      if (Weight != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Weight);
      }
      if (OccurencesInTitle != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(OccurencesInTitle);
      }
      if (OccurencesInLinks != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(OccurencesInLinks);
      }
      if (OccurencesInHeaders != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(OccurencesInHeaders);
      }
      positions_.WriteTo(output, _repeated_positions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IndexId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(IndexId);
      }
      if (key_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Key);
      }
      if (WordFrequency != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WordFrequency);
      }
      if (Weight != 0D) {
        size += 1 + 8;
      }
      if (OccurencesInTitle != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OccurencesInTitle);
      }
      if (OccurencesInLinks != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OccurencesInLinks);
      }
      if (OccurencesInHeaders != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OccurencesInHeaders);
      }
      size += positions_.CalculateSize(_repeated_positions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Index other) {
      if (other == null) {
        return;
      }
      if (other.IndexId != 0UL) {
        IndexId = other.IndexId;
      }
      if (other.key_ != null) {
        if (key_ == null) {
          key_ = new global::XiaoyaStore.Model.IndexKey();
        }
        Key.MergeFrom(other.Key);
      }
      if (other.WordFrequency != 0) {
        WordFrequency = other.WordFrequency;
      }
      if (other.Weight != 0D) {
        Weight = other.Weight;
      }
      if (other.OccurencesInTitle != 0) {
        OccurencesInTitle = other.OccurencesInTitle;
      }
      if (other.OccurencesInLinks != 0) {
        OccurencesInLinks = other.OccurencesInLinks;
      }
      if (other.OccurencesInHeaders != 0) {
        OccurencesInHeaders = other.OccurencesInHeaders;
      }
      positions_.Add(other.positions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IndexId = input.ReadUInt64();
            break;
          }
          case 18: {
            if (key_ == null) {
              key_ = new global::XiaoyaStore.Model.IndexKey();
            }
            input.ReadMessage(key_);
            break;
          }
          case 24: {
            WordFrequency = input.ReadUInt32();
            break;
          }
          case 33: {
            Weight = input.ReadDouble();
            break;
          }
          case 40: {
            OccurencesInTitle = input.ReadUInt32();
            break;
          }
          case 48: {
            OccurencesInLinks = input.ReadUInt32();
            break;
          }
          case 56: {
            OccurencesInHeaders = input.ReadUInt32();
            break;
          }
          case 66:
          case 64: {
            positions_.AddEntriesFrom(input, _repeated_positions_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class UrlFile : pb::IMessage<UrlFile> {
    private static readonly pb::MessageParser<UrlFile> _parser = new pb::MessageParser<UrlFile>(() => new UrlFile());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UrlFile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XiaoyaStore.Model.ModelsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UrlFile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UrlFile(UrlFile other) : this() {
      urlfileId_ = other.urlfileId_;
      url_ = other.url_;
      title_ = other.title_;
      filePath_ = other.filePath_;
      fileHash_ = other.fileHash_;
      content_ = other.content_;
      textContent_ = other.textContent_;
      charset_ = other.charset_;
      mimeType_ = other.mimeType_;
      pageRank_ = other.pageRank_;
      inLinkCount_ = other.inLinkCount_;
      inLinkTotalLength_ = other.inLinkTotalLength_;
      headerCount_ = other.headerCount_;
      headerTotalLength_ = other.headerTotalLength_;
      publishDate_ = other.publishDate_;
      updateInterval_ = other.updateInterval_;
      updatedAt_ = other.updatedAt_;
      createdAt_ = other.createdAt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UrlFile Clone() {
      return new UrlFile(this);
    }

    /// <summary>Field number for the "urlfile_id" field.</summary>
    public const int UrlfileIdFieldNumber = 1;
    private ulong urlfileId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UrlfileId {
      get { return urlfileId_; }
      set {
        urlfileId_ = value;
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 2;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 3;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "file_path" field.</summary>
    public const int FilePathFieldNumber = 4;
    private string filePath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FilePath {
      get { return filePath_; }
      set {
        filePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "file_hash" field.</summary>
    public const int FileHashFieldNumber = 5;
    private string fileHash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FileHash {
      get { return fileHash_; }
      set {
        fileHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 6;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "text_content" field.</summary>
    public const int TextContentFieldNumber = 7;
    private string textContent_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TextContent {
      get { return textContent_; }
      set {
        textContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "charset" field.</summary>
    public const int CharsetFieldNumber = 8;
    private string charset_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Charset {
      get { return charset_; }
      set {
        charset_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mime_type" field.</summary>
    public const int MimeTypeFieldNumber = 9;
    private string mimeType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MimeType {
      get { return mimeType_; }
      set {
        mimeType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "page_rank" field.</summary>
    public const int PageRankFieldNumber = 10;
    private double pageRank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double PageRank {
      get { return pageRank_; }
      set {
        pageRank_ = value;
      }
    }

    /// <summary>Field number for the "in_link_count" field.</summary>
    public const int InLinkCountFieldNumber = 11;
    private uint inLinkCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint InLinkCount {
      get { return inLinkCount_; }
      set {
        inLinkCount_ = value;
      }
    }

    /// <summary>Field number for the "in_link_total_length" field.</summary>
    public const int InLinkTotalLengthFieldNumber = 12;
    private uint inLinkTotalLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint InLinkTotalLength {
      get { return inLinkTotalLength_; }
      set {
        inLinkTotalLength_ = value;
      }
    }

    /// <summary>Field number for the "header_count" field.</summary>
    public const int HeaderCountFieldNumber = 13;
    private uint headerCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint HeaderCount {
      get { return headerCount_; }
      set {
        headerCount_ = value;
      }
    }

    /// <summary>Field number for the "header_total_length" field.</summary>
    public const int HeaderTotalLengthFieldNumber = 14;
    private uint headerTotalLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint HeaderTotalLength {
      get { return headerTotalLength_; }
      set {
        headerTotalLength_ = value;
      }
    }

    /// <summary>Field number for the "publish_date" field.</summary>
    public const int PublishDateFieldNumber = 15;
    private ulong publishDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong PublishDate {
      get { return publishDate_; }
      set {
        publishDate_ = value;
      }
    }

    /// <summary>Field number for the "update_interval" field.</summary>
    public const int UpdateIntervalFieldNumber = 16;
    private ulong updateInterval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UpdateInterval {
      get { return updateInterval_; }
      set {
        updateInterval_ = value;
      }
    }

    /// <summary>Field number for the "updated_at" field.</summary>
    public const int UpdatedAtFieldNumber = 17;
    private ulong updatedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UpdatedAt {
      get { return updatedAt_; }
      set {
        updatedAt_ = value;
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 18;
    private ulong createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UrlFile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UrlFile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UrlfileId != other.UrlfileId) return false;
      if (Url != other.Url) return false;
      if (Title != other.Title) return false;
      if (FilePath != other.FilePath) return false;
      if (FileHash != other.FileHash) return false;
      if (Content != other.Content) return false;
      if (TextContent != other.TextContent) return false;
      if (Charset != other.Charset) return false;
      if (MimeType != other.MimeType) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PageRank, other.PageRank)) return false;
      if (InLinkCount != other.InLinkCount) return false;
      if (InLinkTotalLength != other.InLinkTotalLength) return false;
      if (HeaderCount != other.HeaderCount) return false;
      if (HeaderTotalLength != other.HeaderTotalLength) return false;
      if (PublishDate != other.PublishDate) return false;
      if (UpdateInterval != other.UpdateInterval) return false;
      if (UpdatedAt != other.UpdatedAt) return false;
      if (CreatedAt != other.CreatedAt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UrlfileId != 0UL) hash ^= UrlfileId.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (FilePath.Length != 0) hash ^= FilePath.GetHashCode();
      if (FileHash.Length != 0) hash ^= FileHash.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (TextContent.Length != 0) hash ^= TextContent.GetHashCode();
      if (Charset.Length != 0) hash ^= Charset.GetHashCode();
      if (MimeType.Length != 0) hash ^= MimeType.GetHashCode();
      if (PageRank != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PageRank);
      if (InLinkCount != 0) hash ^= InLinkCount.GetHashCode();
      if (InLinkTotalLength != 0) hash ^= InLinkTotalLength.GetHashCode();
      if (HeaderCount != 0) hash ^= HeaderCount.GetHashCode();
      if (HeaderTotalLength != 0) hash ^= HeaderTotalLength.GetHashCode();
      if (PublishDate != 0UL) hash ^= PublishDate.GetHashCode();
      if (UpdateInterval != 0UL) hash ^= UpdateInterval.GetHashCode();
      if (UpdatedAt != 0UL) hash ^= UpdatedAt.GetHashCode();
      if (CreatedAt != 0UL) hash ^= CreatedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UrlfileId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(UrlfileId);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Title);
      }
      if (FilePath.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FilePath);
      }
      if (FileHash.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FileHash);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Content);
      }
      if (TextContent.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(TextContent);
      }
      if (Charset.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Charset);
      }
      if (MimeType.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(MimeType);
      }
      if (PageRank != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(PageRank);
      }
      if (InLinkCount != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(InLinkCount);
      }
      if (InLinkTotalLength != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(InLinkTotalLength);
      }
      if (HeaderCount != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(HeaderCount);
      }
      if (HeaderTotalLength != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(HeaderTotalLength);
      }
      if (PublishDate != 0UL) {
        output.WriteRawTag(120);
        output.WriteUInt64(PublishDate);
      }
      if (UpdateInterval != 0UL) {
        output.WriteRawTag(128, 1);
        output.WriteUInt64(UpdateInterval);
      }
      if (UpdatedAt != 0UL) {
        output.WriteRawTag(136, 1);
        output.WriteUInt64(UpdatedAt);
      }
      if (CreatedAt != 0UL) {
        output.WriteRawTag(144, 1);
        output.WriteUInt64(CreatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UrlfileId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UrlfileId);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (FilePath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FilePath);
      }
      if (FileHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileHash);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (TextContent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextContent);
      }
      if (Charset.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Charset);
      }
      if (MimeType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MimeType);
      }
      if (PageRank != 0D) {
        size += 1 + 8;
      }
      if (InLinkCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InLinkCount);
      }
      if (InLinkTotalLength != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InLinkTotalLength);
      }
      if (HeaderCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HeaderCount);
      }
      if (HeaderTotalLength != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HeaderTotalLength);
      }
      if (PublishDate != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PublishDate);
      }
      if (UpdateInterval != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(UpdateInterval);
      }
      if (UpdatedAt != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(UpdatedAt);
      }
      if (CreatedAt != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(CreatedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UrlFile other) {
      if (other == null) {
        return;
      }
      if (other.UrlfileId != 0UL) {
        UrlfileId = other.UrlfileId;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.FilePath.Length != 0) {
        FilePath = other.FilePath;
      }
      if (other.FileHash.Length != 0) {
        FileHash = other.FileHash;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.TextContent.Length != 0) {
        TextContent = other.TextContent;
      }
      if (other.Charset.Length != 0) {
        Charset = other.Charset;
      }
      if (other.MimeType.Length != 0) {
        MimeType = other.MimeType;
      }
      if (other.PageRank != 0D) {
        PageRank = other.PageRank;
      }
      if (other.InLinkCount != 0) {
        InLinkCount = other.InLinkCount;
      }
      if (other.InLinkTotalLength != 0) {
        InLinkTotalLength = other.InLinkTotalLength;
      }
      if (other.HeaderCount != 0) {
        HeaderCount = other.HeaderCount;
      }
      if (other.HeaderTotalLength != 0) {
        HeaderTotalLength = other.HeaderTotalLength;
      }
      if (other.PublishDate != 0UL) {
        PublishDate = other.PublishDate;
      }
      if (other.UpdateInterval != 0UL) {
        UpdateInterval = other.UpdateInterval;
      }
      if (other.UpdatedAt != 0UL) {
        UpdatedAt = other.UpdatedAt;
      }
      if (other.CreatedAt != 0UL) {
        CreatedAt = other.CreatedAt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UrlfileId = input.ReadUInt64();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
          case 26: {
            Title = input.ReadString();
            break;
          }
          case 34: {
            FilePath = input.ReadString();
            break;
          }
          case 42: {
            FileHash = input.ReadString();
            break;
          }
          case 50: {
            Content = input.ReadString();
            break;
          }
          case 58: {
            TextContent = input.ReadString();
            break;
          }
          case 66: {
            Charset = input.ReadString();
            break;
          }
          case 74: {
            MimeType = input.ReadString();
            break;
          }
          case 81: {
            PageRank = input.ReadDouble();
            break;
          }
          case 88: {
            InLinkCount = input.ReadUInt32();
            break;
          }
          case 96: {
            InLinkTotalLength = input.ReadUInt32();
            break;
          }
          case 104: {
            HeaderCount = input.ReadUInt32();
            break;
          }
          case 112: {
            HeaderTotalLength = input.ReadUInt32();
            break;
          }
          case 120: {
            PublishDate = input.ReadUInt64();
            break;
          }
          case 128: {
            UpdateInterval = input.ReadUInt64();
            break;
          }
          case 136: {
            UpdatedAt = input.ReadUInt64();
            break;
          }
          case 144: {
            CreatedAt = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Link : pb::IMessage<Link> {
    private static readonly pb::MessageParser<Link> _parser = new pb::MessageParser<Link>(() => new Link());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Link> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XiaoyaStore.Model.ModelsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Link() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Link(Link other) : this() {
      linkId_ = other.linkId_;
      urlfileId_ = other.urlfileId_;
      url_ = other.url_;
      text_ = other.text_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Link Clone() {
      return new Link(this);
    }

    /// <summary>Field number for the "link_id" field.</summary>
    public const int LinkIdFieldNumber = 1;
    private ulong linkId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong LinkId {
      get { return linkId_; }
      set {
        linkId_ = value;
      }
    }

    /// <summary>Field number for the "urlfile_id" field.</summary>
    public const int UrlfileIdFieldNumber = 2;
    private ulong urlfileId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UrlfileId {
      get { return urlfileId_; }
      set {
        urlfileId_ = value;
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 3;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 4;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Link);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Link other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LinkId != other.LinkId) return false;
      if (UrlfileId != other.UrlfileId) return false;
      if (Url != other.Url) return false;
      if (Text != other.Text) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LinkId != 0UL) hash ^= LinkId.GetHashCode();
      if (UrlfileId != 0UL) hash ^= UrlfileId.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LinkId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(LinkId);
      }
      if (UrlfileId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(UrlfileId);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Url);
      }
      if (Text.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LinkId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LinkId);
      }
      if (UrlfileId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UrlfileId);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Link other) {
      if (other == null) {
        return;
      }
      if (other.LinkId != 0UL) {
        LinkId = other.LinkId;
      }
      if (other.UrlfileId != 0UL) {
        UrlfileId = other.UrlfileId;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LinkId = input.ReadUInt64();
            break;
          }
          case 16: {
            UrlfileId = input.ReadUInt64();
            break;
          }
          case 26: {
            Url = input.ReadString();
            break;
          }
          case 34: {
            Text = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class IdList : pb::IMessage<IdList> {
    private static readonly pb::MessageParser<IdList> _parser = new pb::MessageParser<IdList>(() => new IdList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IdList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XiaoyaStore.Model.ModelsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdList(IdList other) : this() {
      ids_ = other.ids_.Clone();
      isAdd_ = other.isAdd_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdList Clone() {
      return new IdList(this);
    }

    /// <summary>Field number for the "ids" field.</summary>
    public const int IdsFieldNumber = 1;
    private static readonly pb::FieldCodec<ulong> _repeated_ids_codec
        = pb::FieldCodec.ForUInt64(10);
    private readonly pbc::RepeatedField<ulong> ids_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> Ids {
      get { return ids_; }
    }

    /// <summary>Field number for the "is_add" field.</summary>
    public const int IsAddFieldNumber = 2;
    private bool isAdd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsAdd {
      get { return isAdd_; }
      set {
        isAdd_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IdList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IdList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!ids_.Equals(other.ids_)) return false;
      if (IsAdd != other.IsAdd) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= ids_.GetHashCode();
      if (IsAdd != false) hash ^= IsAdd.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      ids_.WriteTo(output, _repeated_ids_codec);
      if (IsAdd != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsAdd);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += ids_.CalculateSize(_repeated_ids_codec);
      if (IsAdd != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IdList other) {
      if (other == null) {
        return;
      }
      ids_.Add(other.ids_);
      if (other.IsAdd != false) {
        IsAdd = other.IsAdd;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            ids_.AddEntriesFrom(input, _repeated_ids_codec);
            break;
          }
          case 16: {
            IsAdd = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
