// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using XiaoyaCommon.Data.Crawler;

namespace XiaoyaCommon.Migrations
{
    [DbContext(typeof(CrawlerContext))]
    [Migration("20180203045931_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("XiaoyaCommon.Data.Crawler.Model.UrlFile", b =>
                {
                    b.Property<int>("UrlFileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Charset");

                    b.Property<string>("FilePath");

                    b.Property<string>("MimeType");

                    b.Property<string>("Url");

                    b.HasKey("UrlFileId");

                    b.ToTable("UrlFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
