
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : models_types.cpp
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

#include "stdafx.h"

#include "models_reflection.h"
#include <bond/core/exception.h>

namespace XiaoyaStore
{
namespace Model
{
    
    const ::bond::Metadata UrlFrontierItem::Schema::metadata
        = UrlFrontierItem::Schema::GetMetadata();
    
    const ::bond::Metadata UrlFrontierItem::Schema::s_Url_metadata
        = ::bond::reflection::MetadataInit("Url");
    
    const ::bond::Metadata UrlFrontierItem::Schema::s_PlannedTime_metadata
        = ::bond::reflection::MetadataInit("PlannedTime");
    
    const ::bond::Metadata UrlFrontierItem::Schema::s_Priority_metadata
        = ::bond::reflection::MetadataInit("Priority");
    
    const ::bond::Metadata UrlFrontierItem::Schema::s_FailedTimes_metadata
        = ::bond::reflection::MetadataInit("FailedTimes");
    
    const ::bond::Metadata UrlFrontierItem::Schema::s_UrlFileId_metadata
        = ::bond::reflection::MetadataInit("UrlFileId");
    
    const ::bond::Metadata UrlFrontierItem::Schema::s_UpdatedAt_metadata
        = ::bond::reflection::MetadataInit("UpdatedAt");
    
    const ::bond::Metadata UrlFrontierItem::Schema::s_CreatedAt_metadata
        = ::bond::reflection::MetadataInit("CreatedAt");

    
    const ::bond::Metadata PostingList::Schema::metadata
        = PostingList::Schema::GetMetadata();
    
    const ::bond::Metadata PostingList::Schema::s_Word_metadata
        = ::bond::reflection::MetadataInit("Word");
    
    const ::bond::Metadata PostingList::Schema::s_WordFrequency_metadata
        = ::bond::reflection::MetadataInit("WordFrequency");
    
    const ::bond::Metadata PostingList::Schema::s_DocumentFrequency_metadata
        = ::bond::reflection::MetadataInit("DocumentFrequency");
    
    const ::bond::Metadata PostingList::Schema::s_Postings_metadata
        = ::bond::reflection::MetadataInit("Postings");
    
    const ::bond::Metadata PostingList::Schema::s_IsAdd_metadata
        = ::bond::reflection::MetadataInit(true, "IsAdd");

    
    const ::bond::Metadata IndexKey::Schema::metadata
        = IndexKey::Schema::GetMetadata();
    
    const ::bond::Metadata IndexKey::Schema::s_UrlFileId_metadata
        = ::bond::reflection::MetadataInit("UrlFileId");
    
    const ::bond::Metadata IndexKey::Schema::s_Word_metadata
        = ::bond::reflection::MetadataInit("Word");

    
    const ::bond::Metadata Index::Schema::metadata
        = Index::Schema::GetMetadata();
    
    const ::bond::Metadata Index::Schema::s_IndexId_metadata
        = ::bond::reflection::MetadataInit("IndexId");
    
    const ::bond::Metadata Index::Schema::s_Key_metadata
        = ::bond::reflection::MetadataInit("Key");
    
    const ::bond::Metadata Index::Schema::s_WordFrequency_metadata
        = ::bond::reflection::MetadataInit("WordFrequency");
    
    const ::bond::Metadata Index::Schema::s_Weight_metadata
        = ::bond::reflection::MetadataInit("Weight");
    
    const ::bond::Metadata Index::Schema::s_OccurencesInTitle_metadata
        = ::bond::reflection::MetadataInit("OccurencesInTitle");
    
    const ::bond::Metadata Index::Schema::s_OccurencesInLinks_metadata
        = ::bond::reflection::MetadataInit("OccurencesInLinks");
    
    const ::bond::Metadata Index::Schema::s_OccurencesInHeaders_metadata
        = ::bond::reflection::MetadataInit("OccurencesInHeaders");
    
    const ::bond::Metadata Index::Schema::s_Positions_metadata
        = ::bond::reflection::MetadataInit("Positions");

    
    const ::bond::Metadata UrlFile::Schema::metadata
        = UrlFile::Schema::GetMetadata();
    
    const ::bond::Metadata UrlFile::Schema::s_UrlFileId_metadata
        = ::bond::reflection::MetadataInit(static_cast<uint64_t>(0ULL), "UrlFileId");
    
    const ::bond::Metadata UrlFile::Schema::s_Url_metadata
        = ::bond::reflection::MetadataInit("Url");
    
    const ::bond::Metadata UrlFile::Schema::s_Title_metadata
        = ::bond::reflection::MetadataInit("Title");
    
    const ::bond::Metadata UrlFile::Schema::s_FilePath_metadata
        = ::bond::reflection::MetadataInit("FilePath");
    
    const ::bond::Metadata UrlFile::Schema::s_FileHash_metadata
        = ::bond::reflection::MetadataInit("FileHash");
    
    const ::bond::Metadata UrlFile::Schema::s_Content_metadata
        = ::bond::reflection::MetadataInit("Content");
    
    const ::bond::Metadata UrlFile::Schema::s_TextContent_metadata
        = ::bond::reflection::MetadataInit("TextContent");
    
    const ::bond::Metadata UrlFile::Schema::s_Charset_metadata
        = ::bond::reflection::MetadataInit("Charset");
    
    const ::bond::Metadata UrlFile::Schema::s_MimeType_metadata
        = ::bond::reflection::MetadataInit("MimeType");
    
    const ::bond::Metadata UrlFile::Schema::s_PageRank_metadata
        = ::bond::reflection::MetadataInit("PageRank");
    
    const ::bond::Metadata UrlFile::Schema::s_InLinkCount_metadata
        = ::bond::reflection::MetadataInit("InLinkCount");
    
    const ::bond::Metadata UrlFile::Schema::s_InLinkTotalLength_metadata
        = ::bond::reflection::MetadataInit("InLinkTotalLength");
    
    const ::bond::Metadata UrlFile::Schema::s_HeaderCount_metadata
        = ::bond::reflection::MetadataInit("HeaderCount");
    
    const ::bond::Metadata UrlFile::Schema::s_HeaderTotalLength_metadata
        = ::bond::reflection::MetadataInit("HeaderTotalLength");
    
    const ::bond::Metadata UrlFile::Schema::s_PublishDate_metadata
        = ::bond::reflection::MetadataInit("PublishDate");
    
    const ::bond::Metadata UrlFile::Schema::s_UpdateInterval_metadata
        = ::bond::reflection::MetadataInit("UpdateInterval");
    
    const ::bond::Metadata UrlFile::Schema::s_UpdatedAt_metadata
        = ::bond::reflection::MetadataInit("UpdatedAt");
    
    const ::bond::Metadata UrlFile::Schema::s_CreatedAt_metadata
        = ::bond::reflection::MetadataInit("CreatedAt");

    
    const ::bond::Metadata Link::Schema::metadata
        = Link::Schema::GetMetadata();
    
    const ::bond::Metadata Link::Schema::s_LinkId_metadata
        = ::bond::reflection::MetadataInit("LinkId");
    
    const ::bond::Metadata Link::Schema::s_UrlFileId_metadata
        = ::bond::reflection::MetadataInit("UrlFileId");
    
    const ::bond::Metadata Link::Schema::s_Url_metadata
        = ::bond::reflection::MetadataInit("Url");
    
    const ::bond::Metadata Link::Schema::s_Text_metadata
        = ::bond::reflection::MetadataInit("Text");

    
    const ::bond::Metadata IdList::Schema::metadata
        = IdList::Schema::GetMetadata();
    
    const ::bond::Metadata IdList::Schema::s_Ids_metadata
        = ::bond::reflection::MetadataInit("Ids");
    
    const ::bond::Metadata IdList::Schema::s_IsAdd_metadata
        = ::bond::reflection::MetadataInit(true, "IsAdd");

    
} // namespace Model
} // namespace XiaoyaStore
