
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : models_apply.cpp
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

#include "stdafx.h"

#include "models_apply.h"
#include "models_reflection.h"

namespace bond
{
    
    //
    // Extern template specializations of Apply function with common
    // transforms for UrlFrontierItem.
    //

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFrontierItem>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem>& value);

    template 
    bool Apply(const ::bond::InitSchemaDef& transform,
               const ::XiaoyaStore::Model::UrlFrontierItem& value);

    template 
    bool Apply(const ::bond::Null& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem, ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFrontierItem>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFrontierItem>& transform,
               const ::bond::bonded<void,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFrontierItem& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFrontierItem& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::UrlFrontierItem& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::UrlFrontierItem& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFrontierItem>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFrontierItem>& transform,
               const ::bond::bonded<void,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFrontierItem& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFrontierItem& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFrontierItem>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFrontierItem>& transform,
               const ::bond::bonded<void,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFrontierItem& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFrontierItem& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFrontierItem,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    //
    // Extern template specializations of Apply function with common
    // transforms for PostingList.
    //

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::PostingList>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList>& value);

    template 
    bool Apply(const ::bond::InitSchemaDef& transform,
               const ::XiaoyaStore::Model::PostingList& value);

    template 
    bool Apply(const ::bond::Null& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList, ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::PostingList>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::PostingList>& transform,
               const ::bond::bonded<void,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::PostingList& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::PostingList& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::PostingList& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::PostingList& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::PostingList>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::PostingList>& transform,
               const ::bond::bonded<void,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::PostingList& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::PostingList& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::PostingList>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::PostingList>& transform,
               const ::bond::bonded<void,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::PostingList& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::PostingList& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::PostingList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    //
    // Extern template specializations of Apply function with common
    // transforms for IndexKey.
    //

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IndexKey>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey>& value);

    template 
    bool Apply(const ::bond::InitSchemaDef& transform,
               const ::XiaoyaStore::Model::IndexKey& value);

    template 
    bool Apply(const ::bond::Null& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey, ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IndexKey>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IndexKey>& transform,
               const ::bond::bonded<void,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IndexKey& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IndexKey& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::IndexKey& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::IndexKey& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IndexKey>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IndexKey>& transform,
               const ::bond::bonded<void,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IndexKey& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IndexKey& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IndexKey>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IndexKey>& transform,
               const ::bond::bonded<void,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IndexKey& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IndexKey& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IndexKey,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    //
    // Extern template specializations of Apply function with common
    // transforms for Index.
    //

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Index>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index>& value);

    template 
    bool Apply(const ::bond::InitSchemaDef& transform,
               const ::XiaoyaStore::Model::Index& value);

    template 
    bool Apply(const ::bond::Null& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index, ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Index>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Index>& transform,
               const ::bond::bonded<void,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Index& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Index& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::Index& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::Index& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Index>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Index>& transform,
               const ::bond::bonded<void,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Index& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Index& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Index>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Index>& transform,
               const ::bond::bonded<void,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Index& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Index& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Index,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    //
    // Extern template specializations of Apply function with common
    // transforms for UrlFile.
    //

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFile>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile>& value);

    template 
    bool Apply(const ::bond::InitSchemaDef& transform,
               const ::XiaoyaStore::Model::UrlFile& value);

    template 
    bool Apply(const ::bond::Null& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile, ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFile>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFile>& transform,
               const ::bond::bonded<void,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFile& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFile& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::UrlFile& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::UrlFile& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFile>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFile>& transform,
               const ::bond::bonded<void,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFile& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFile& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFile>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::UrlFile>& transform,
               const ::bond::bonded<void,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFile& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::UrlFile& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::UrlFile,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    //
    // Extern template specializations of Apply function with common
    // transforms for Link.
    //

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Link>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link>& value);

    template 
    bool Apply(const ::bond::InitSchemaDef& transform,
               const ::XiaoyaStore::Model::Link& value);

    template 
    bool Apply(const ::bond::Null& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link, ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Link>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Link>& transform,
               const ::bond::bonded<void,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Link& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Link& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::Link& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::Link& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Link>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Link>& transform,
               const ::bond::bonded<void,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Link& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Link& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Link>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::Link>& transform,
               const ::bond::bonded<void,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Link& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::Link& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::Link,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    //
    // Extern template specializations of Apply function with common
    // transforms for IdList.
    //

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IdList>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList>& value);

    template 
    bool Apply(const ::bond::InitSchemaDef& transform,
               const ::XiaoyaStore::Model::IdList& value);

    template 
    bool Apply(const ::bond::Null& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList, ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IdList>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IdList>& transform,
               const ::bond::bonded<void,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IdList& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IdList& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::IdList& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::XiaoyaStore::Model::IdList& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::CompactBinaryWriter< ::bond::CompactBinaryCounter::type> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IdList>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IdList>& transform,
               const ::bond::bonded<void,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IdList& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IdList& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::FastBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IdList>& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);

    template 
    bool Apply(const ::bond::To< ::XiaoyaStore::Model::IdList>& transform,
               const ::bond::bonded<void,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IdList& value);

    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Serializer< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::XiaoyaStore::Model::IdList& value);

    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::CompactBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::FastBinaryReader< ::bond::InputBuffer>&>& value);
    
    template 
    bool Apply(const ::bond::Marshaler< ::bond::SimpleBinaryWriter< ::bond::OutputBuffer> >& transform,
               const ::bond::bonded< ::XiaoyaStore::Model::IdList,  ::bond::SimpleBinaryReader< ::bond::InputBuffer>&>& value);
    
} // namespace bond
