// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rpc.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace XiaoyaStore.Service {
  public static partial class UrlFrontierItemService
  {
    static readonly string __ServiceName = "XiaoyaStore.Service.UrlFrontierItemService";

    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgUrls> __Marshaller_ArgUrls = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgUrls.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.Result> __Marshaller_Result = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.Result.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgVoid> __Marshaller_ArgVoid = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgVoid.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgPushBackUrl> __Marshaller_ArgPushBackUrl = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgPushBackUrl.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ResultWithUrl> __Marshaller_ResultWithUrl = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ResultWithUrl.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgUrl> __Marshaller_ArgUrl = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgUrl.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgHost> __Marshaller_ArgHost = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgHost.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ResultWithCount> __Marshaller_ResultWithCount = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ResultWithCount.Parser.ParseFrom);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgUrls, global::XiaoyaStore.Service.Result> __Method_Init = new grpc::Method<global::XiaoyaStore.Service.ArgUrls, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Init",
        __Marshaller_ArgUrls,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgVoid, global::XiaoyaStore.Service.Result> __Method_Reload = new grpc::Method<global::XiaoyaStore.Service.ArgVoid, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Reload",
        __Marshaller_ArgVoid,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgUrls, global::XiaoyaStore.Service.Result> __Method_PushUrls = new grpc::Method<global::XiaoyaStore.Service.ArgUrls, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PushUrls",
        __Marshaller_ArgUrls,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgPushBackUrl, global::XiaoyaStore.Service.Result> __Method_PushBackUrl = new grpc::Method<global::XiaoyaStore.Service.ArgPushBackUrl, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PushBackUrl",
        __Marshaller_ArgPushBackUrl,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgVoid, global::XiaoyaStore.Service.ResultWithUrl> __Method_PopUrl = new grpc::Method<global::XiaoyaStore.Service.ArgVoid, global::XiaoyaStore.Service.ResultWithUrl>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PopUrl",
        __Marshaller_ArgVoid,
        __Marshaller_ResultWithUrl);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgUrl, global::XiaoyaStore.Service.Result> __Method_RemoveUrl = new grpc::Method<global::XiaoyaStore.Service.ArgUrl, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveUrl",
        __Marshaller_ArgUrl,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgHost, global::XiaoyaStore.Service.ResultWithCount> __Method_GetHostCount = new grpc::Method<global::XiaoyaStore.Service.ArgHost, global::XiaoyaStore.Service.ResultWithCount>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetHostCount",
        __Marshaller_ArgHost,
        __Marshaller_ResultWithCount);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::XiaoyaStore.Service.RpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UrlFrontierItemService</summary>
    public abstract partial class UrlFrontierItemServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> Init(global::XiaoyaStore.Service.ArgUrls request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> Reload(global::XiaoyaStore.Service.ArgVoid request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> PushUrls(global::XiaoyaStore.Service.ArgUrls request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> PushBackUrl(global::XiaoyaStore.Service.ArgPushBackUrl request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithUrl> PopUrl(global::XiaoyaStore.Service.ArgVoid request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> RemoveUrl(global::XiaoyaStore.Service.ArgUrl request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithCount> GetHostCount(global::XiaoyaStore.Service.ArgHost request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UrlFrontierItemService</summary>
    public partial class UrlFrontierItemServiceClient : grpc::ClientBase<UrlFrontierItemServiceClient>
    {
      /// <summary>Creates a new client for UrlFrontierItemService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UrlFrontierItemServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UrlFrontierItemService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UrlFrontierItemServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UrlFrontierItemServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UrlFrontierItemServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::XiaoyaStore.Service.Result Init(global::XiaoyaStore.Service.ArgUrls request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Init(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result Init(global::XiaoyaStore.Service.ArgUrls request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Init, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> InitAsync(global::XiaoyaStore.Service.ArgUrls request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return InitAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> InitAsync(global::XiaoyaStore.Service.ArgUrls request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Init, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.Result Reload(global::XiaoyaStore.Service.ArgVoid request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Reload(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result Reload(global::XiaoyaStore.Service.ArgVoid request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Reload, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ReloadAsync(global::XiaoyaStore.Service.ArgVoid request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ReloadAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ReloadAsync(global::XiaoyaStore.Service.ArgVoid request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Reload, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.Result PushUrls(global::XiaoyaStore.Service.ArgUrls request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PushUrls(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result PushUrls(global::XiaoyaStore.Service.ArgUrls request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PushUrls, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> PushUrlsAsync(global::XiaoyaStore.Service.ArgUrls request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PushUrlsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> PushUrlsAsync(global::XiaoyaStore.Service.ArgUrls request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PushUrls, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.Result PushBackUrl(global::XiaoyaStore.Service.ArgPushBackUrl request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PushBackUrl(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result PushBackUrl(global::XiaoyaStore.Service.ArgPushBackUrl request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PushBackUrl, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> PushBackUrlAsync(global::XiaoyaStore.Service.ArgPushBackUrl request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PushBackUrlAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> PushBackUrlAsync(global::XiaoyaStore.Service.ArgPushBackUrl request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PushBackUrl, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.ResultWithUrl PopUrl(global::XiaoyaStore.Service.ArgVoid request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PopUrl(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithUrl PopUrl(global::XiaoyaStore.Service.ArgVoid request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PopUrl, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrl> PopUrlAsync(global::XiaoyaStore.Service.ArgVoid request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PopUrlAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrl> PopUrlAsync(global::XiaoyaStore.Service.ArgVoid request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PopUrl, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.Result RemoveUrl(global::XiaoyaStore.Service.ArgUrl request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RemoveUrl(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result RemoveUrl(global::XiaoyaStore.Service.ArgUrl request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveUrl, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> RemoveUrlAsync(global::XiaoyaStore.Service.ArgUrl request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RemoveUrlAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> RemoveUrlAsync(global::XiaoyaStore.Service.ArgUrl request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveUrl, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.ResultWithCount GetHostCount(global::XiaoyaStore.Service.ArgHost request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetHostCount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithCount GetHostCount(global::XiaoyaStore.Service.ArgHost request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetHostCount, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithCount> GetHostCountAsync(global::XiaoyaStore.Service.ArgHost request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetHostCountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithCount> GetHostCountAsync(global::XiaoyaStore.Service.ArgHost request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetHostCount, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UrlFrontierItemServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UrlFrontierItemServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UrlFrontierItemServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Init, serviceImpl.Init)
          .AddMethod(__Method_Reload, serviceImpl.Reload)
          .AddMethod(__Method_PushUrls, serviceImpl.PushUrls)
          .AddMethod(__Method_PushBackUrl, serviceImpl.PushBackUrl)
          .AddMethod(__Method_PopUrl, serviceImpl.PopUrl)
          .AddMethod(__Method_RemoveUrl, serviceImpl.RemoveUrl)
          .AddMethod(__Method_GetHostCount, serviceImpl.GetHostCount).Build();
    }

  }
  public static partial class UrlFileService
  {
    static readonly string __ServiceName = "XiaoyaStore.Service.UrlFileService";

    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgId> __Marshaller_ArgId = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgId.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ResultWithUrlFile> __Marshaller_ResultWithUrlFile = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ResultWithUrlFile.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgUrl> __Marshaller_ArgUrl = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgUrl.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgHash> __Marshaller_ArgHash = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgHash.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ResultWithUrlFiles> __Marshaller_ResultWithUrlFiles = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ResultWithUrlFiles.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgUrlFile> __Marshaller_ArgUrlFile = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgUrlFile.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ResultWithUrlFileAndOldId> __Marshaller_ResultWithUrlFileAndOldId = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ResultWithUrlFileAndOldId.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgVoid> __Marshaller_ArgVoid = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgVoid.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ResultWithCount> __Marshaller_ResultWithCount = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ResultWithCount.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.Result> __Marshaller_Result = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.Result.Parser.ParseFrom);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.ResultWithUrlFile> __Method_GetUrlFileById = new grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.ResultWithUrlFile>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUrlFileById",
        __Marshaller_ArgId,
        __Marshaller_ResultWithUrlFile);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgUrl, global::XiaoyaStore.Service.ResultWithUrlFile> __Method_GetUrlFileByUrl = new grpc::Method<global::XiaoyaStore.Service.ArgUrl, global::XiaoyaStore.Service.ResultWithUrlFile>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUrlFileByUrl",
        __Marshaller_ArgUrl,
        __Marshaller_ResultWithUrlFile);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgHash, global::XiaoyaStore.Service.ResultWithUrlFiles> __Method_GetUrlFilesByHash = new grpc::Method<global::XiaoyaStore.Service.ArgHash, global::XiaoyaStore.Service.ResultWithUrlFiles>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUrlFilesByHash",
        __Marshaller_ArgHash,
        __Marshaller_ResultWithUrlFiles);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgUrlFile, global::XiaoyaStore.Service.ResultWithUrlFileAndOldId> __Method_SaveUrlFileAndGetOldId = new grpc::Method<global::XiaoyaStore.Service.ArgUrlFile, global::XiaoyaStore.Service.ResultWithUrlFileAndOldId>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveUrlFileAndGetOldId",
        __Marshaller_ArgUrlFile,
        __Marshaller_ResultWithUrlFileAndOldId);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgVoid, global::XiaoyaStore.Service.ResultWithCount> __Method_GetCount = new grpc::Method<global::XiaoyaStore.Service.ArgVoid, global::XiaoyaStore.Service.ResultWithCount>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCount",
        __Marshaller_ArgVoid,
        __Marshaller_ResultWithCount);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.Result> __Method_ContainsId = new grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ContainsId",
        __Marshaller_ArgId,
        __Marshaller_Result);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::XiaoyaStore.Service.RpcReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of UrlFileService</summary>
    public abstract partial class UrlFileServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithUrlFile> GetUrlFileById(global::XiaoyaStore.Service.ArgId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithUrlFile> GetUrlFileByUrl(global::XiaoyaStore.Service.ArgUrl request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithUrlFiles> GetUrlFilesByHash(global::XiaoyaStore.Service.ArgHash request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithUrlFileAndOldId> SaveUrlFileAndGetOldId(global::XiaoyaStore.Service.ArgUrlFile request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithCount> GetCount(global::XiaoyaStore.Service.ArgVoid request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> ContainsId(global::XiaoyaStore.Service.ArgId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UrlFileService</summary>
    public partial class UrlFileServiceClient : grpc::ClientBase<UrlFileServiceClient>
    {
      /// <summary>Creates a new client for UrlFileService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UrlFileServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UrlFileService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UrlFileServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UrlFileServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UrlFileServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::XiaoyaStore.Service.ResultWithUrlFile GetUrlFileById(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUrlFileById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithUrlFile GetUrlFileById(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUrlFileById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrlFile> GetUrlFileByIdAsync(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUrlFileByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrlFile> GetUrlFileByIdAsync(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUrlFileById, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.ResultWithUrlFile GetUrlFileByUrl(global::XiaoyaStore.Service.ArgUrl request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUrlFileByUrl(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithUrlFile GetUrlFileByUrl(global::XiaoyaStore.Service.ArgUrl request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUrlFileByUrl, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrlFile> GetUrlFileByUrlAsync(global::XiaoyaStore.Service.ArgUrl request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUrlFileByUrlAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrlFile> GetUrlFileByUrlAsync(global::XiaoyaStore.Service.ArgUrl request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUrlFileByUrl, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.ResultWithUrlFiles GetUrlFilesByHash(global::XiaoyaStore.Service.ArgHash request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUrlFilesByHash(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithUrlFiles GetUrlFilesByHash(global::XiaoyaStore.Service.ArgHash request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUrlFilesByHash, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrlFiles> GetUrlFilesByHashAsync(global::XiaoyaStore.Service.ArgHash request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUrlFilesByHashAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrlFiles> GetUrlFilesByHashAsync(global::XiaoyaStore.Service.ArgHash request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUrlFilesByHash, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.ResultWithUrlFileAndOldId SaveUrlFileAndGetOldId(global::XiaoyaStore.Service.ArgUrlFile request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SaveUrlFileAndGetOldId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithUrlFileAndOldId SaveUrlFileAndGetOldId(global::XiaoyaStore.Service.ArgUrlFile request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveUrlFileAndGetOldId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrlFileAndOldId> SaveUrlFileAndGetOldIdAsync(global::XiaoyaStore.Service.ArgUrlFile request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SaveUrlFileAndGetOldIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithUrlFileAndOldId> SaveUrlFileAndGetOldIdAsync(global::XiaoyaStore.Service.ArgUrlFile request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveUrlFileAndGetOldId, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.ResultWithCount GetCount(global::XiaoyaStore.Service.ArgVoid request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetCount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithCount GetCount(global::XiaoyaStore.Service.ArgVoid request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCount, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithCount> GetCountAsync(global::XiaoyaStore.Service.ArgVoid request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetCountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithCount> GetCountAsync(global::XiaoyaStore.Service.ArgVoid request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCount, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.Result ContainsId(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ContainsId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result ContainsId(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ContainsId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ContainsIdAsync(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ContainsIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ContainsIdAsync(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ContainsId, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UrlFileServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UrlFileServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UrlFileServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetUrlFileById, serviceImpl.GetUrlFileById)
          .AddMethod(__Method_GetUrlFileByUrl, serviceImpl.GetUrlFileByUrl)
          .AddMethod(__Method_GetUrlFilesByHash, serviceImpl.GetUrlFilesByHash)
          .AddMethod(__Method_SaveUrlFileAndGetOldId, serviceImpl.SaveUrlFileAndGetOldId)
          .AddMethod(__Method_GetCount, serviceImpl.GetCount)
          .AddMethod(__Method_ContainsId, serviceImpl.ContainsId).Build();
    }

  }
  public static partial class PostingListService
  {
    static readonly string __ServiceName = "XiaoyaStore.Service.PostingListService";

    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgSavePostingLists> __Marshaller_ArgSavePostingLists = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgSavePostingLists.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.Result> __Marshaller_Result = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.Result.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgId> __Marshaller_ArgId = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgId.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgWord> __Marshaller_ArgWord = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgWord.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ResultWithPostingList> __Marshaller_ResultWithPostingList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ResultWithPostingList.Parser.ParseFrom);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgSavePostingLists, global::XiaoyaStore.Service.Result> __Method_SavePostingLists = new grpc::Method<global::XiaoyaStore.Service.ArgSavePostingLists, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SavePostingLists",
        __Marshaller_ArgSavePostingLists,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.Result> __Method_ClearPostingLists = new grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ClearPostingLists",
        __Marshaller_ArgId,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgWord, global::XiaoyaStore.Service.ResultWithPostingList> __Method_GetPostingList = new grpc::Method<global::XiaoyaStore.Service.ArgWord, global::XiaoyaStore.Service.ResultWithPostingList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPostingList",
        __Marshaller_ArgWord,
        __Marshaller_ResultWithPostingList);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::XiaoyaStore.Service.RpcReflection.Descriptor.Services[2]; }
    }

    /// <summary>Base class for server-side implementations of PostingListService</summary>
    public abstract partial class PostingListServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> SavePostingLists(global::XiaoyaStore.Service.ArgSavePostingLists request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> ClearPostingLists(global::XiaoyaStore.Service.ArgId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithPostingList> GetPostingList(global::XiaoyaStore.Service.ArgWord request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PostingListService</summary>
    public partial class PostingListServiceClient : grpc::ClientBase<PostingListServiceClient>
    {
      /// <summary>Creates a new client for PostingListService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PostingListServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PostingListService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PostingListServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PostingListServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PostingListServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::XiaoyaStore.Service.Result SavePostingLists(global::XiaoyaStore.Service.ArgSavePostingLists request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SavePostingLists(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result SavePostingLists(global::XiaoyaStore.Service.ArgSavePostingLists request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SavePostingLists, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> SavePostingListsAsync(global::XiaoyaStore.Service.ArgSavePostingLists request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SavePostingListsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> SavePostingListsAsync(global::XiaoyaStore.Service.ArgSavePostingLists request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SavePostingLists, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.Result ClearPostingLists(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ClearPostingLists(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result ClearPostingLists(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ClearPostingLists, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ClearPostingListsAsync(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ClearPostingListsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ClearPostingListsAsync(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ClearPostingLists, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.ResultWithPostingList GetPostingList(global::XiaoyaStore.Service.ArgWord request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetPostingList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithPostingList GetPostingList(global::XiaoyaStore.Service.ArgWord request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPostingList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithPostingList> GetPostingListAsync(global::XiaoyaStore.Service.ArgWord request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetPostingListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithPostingList> GetPostingListAsync(global::XiaoyaStore.Service.ArgWord request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPostingList, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PostingListServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PostingListServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PostingListServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SavePostingLists, serviceImpl.SavePostingLists)
          .AddMethod(__Method_ClearPostingLists, serviceImpl.ClearPostingLists)
          .AddMethod(__Method_GetPostingList, serviceImpl.GetPostingList).Build();
    }

  }
  public static partial class LinkService
  {
    static readonly string __ServiceName = "XiaoyaStore.Service.LinkService";

    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgSaveLinks> __Marshaller_ArgSaveLinks = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgSaveLinks.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.Result> __Marshaller_Result = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.Result.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgId> __Marshaller_ArgId = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgId.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgUrl> __Marshaller_ArgUrl = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgUrl.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ResultWithLinks> __Marshaller_ResultWithLinks = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ResultWithLinks.Parser.ParseFrom);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgSaveLinks, global::XiaoyaStore.Service.Result> __Method_SaveLinks = new grpc::Method<global::XiaoyaStore.Service.ArgSaveLinks, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveLinks",
        __Marshaller_ArgSaveLinks,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.Result> __Method_ClearLinks = new grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ClearLinks",
        __Marshaller_ArgId,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgUrl, global::XiaoyaStore.Service.ResultWithLinks> __Method_GetLinks = new grpc::Method<global::XiaoyaStore.Service.ArgUrl, global::XiaoyaStore.Service.ResultWithLinks>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLinks",
        __Marshaller_ArgUrl,
        __Marshaller_ResultWithLinks);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::XiaoyaStore.Service.RpcReflection.Descriptor.Services[3]; }
    }

    /// <summary>Base class for server-side implementations of LinkService</summary>
    public abstract partial class LinkServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> SaveLinks(global::XiaoyaStore.Service.ArgSaveLinks request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> ClearLinks(global::XiaoyaStore.Service.ArgId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithLinks> GetLinks(global::XiaoyaStore.Service.ArgUrl request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LinkService</summary>
    public partial class LinkServiceClient : grpc::ClientBase<LinkServiceClient>
    {
      /// <summary>Creates a new client for LinkService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LinkServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LinkService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LinkServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LinkServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LinkServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::XiaoyaStore.Service.Result SaveLinks(global::XiaoyaStore.Service.ArgSaveLinks request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SaveLinks(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result SaveLinks(global::XiaoyaStore.Service.ArgSaveLinks request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveLinks, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> SaveLinksAsync(global::XiaoyaStore.Service.ArgSaveLinks request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SaveLinksAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> SaveLinksAsync(global::XiaoyaStore.Service.ArgSaveLinks request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveLinks, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.Result ClearLinks(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ClearLinks(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result ClearLinks(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ClearLinks, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ClearLinksAsync(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ClearLinksAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ClearLinksAsync(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ClearLinks, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.ResultWithLinks GetLinks(global::XiaoyaStore.Service.ArgUrl request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetLinks(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithLinks GetLinks(global::XiaoyaStore.Service.ArgUrl request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLinks, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithLinks> GetLinksAsync(global::XiaoyaStore.Service.ArgUrl request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetLinksAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithLinks> GetLinksAsync(global::XiaoyaStore.Service.ArgUrl request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLinks, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LinkServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LinkServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LinkServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SaveLinks, serviceImpl.SaveLinks)
          .AddMethod(__Method_ClearLinks, serviceImpl.ClearLinks)
          .AddMethod(__Method_GetLinks, serviceImpl.GetLinks).Build();
    }

  }
  public static partial class InvertedIndexService
  {
    static readonly string __ServiceName = "XiaoyaStore.Service.InvertedIndexService";

    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgId> __Marshaller_ArgId = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgId.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.Result> __Marshaller_Result = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.Result.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgSaveIndices> __Marshaller_ArgSaveIndices = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgSaveIndices.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ArgIndexKey> __Marshaller_ArgIndexKey = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ArgIndexKey.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::XiaoyaStore.Service.ResultWithIndex> __Marshaller_ResultWithIndex = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::XiaoyaStore.Service.ResultWithIndex.Parser.ParseFrom);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.Result> __Method_ClearIndices = new grpc::Method<global::XiaoyaStore.Service.ArgId, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ClearIndices",
        __Marshaller_ArgId,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgSaveIndices, global::XiaoyaStore.Service.Result> __Method_SaveIndices = new grpc::Method<global::XiaoyaStore.Service.ArgSaveIndices, global::XiaoyaStore.Service.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveIndices",
        __Marshaller_ArgSaveIndices,
        __Marshaller_Result);

    static readonly grpc::Method<global::XiaoyaStore.Service.ArgIndexKey, global::XiaoyaStore.Service.ResultWithIndex> __Method_GetIndex = new grpc::Method<global::XiaoyaStore.Service.ArgIndexKey, global::XiaoyaStore.Service.ResultWithIndex>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetIndex",
        __Marshaller_ArgIndexKey,
        __Marshaller_ResultWithIndex);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::XiaoyaStore.Service.RpcReflection.Descriptor.Services[4]; }
    }

    /// <summary>Base class for server-side implementations of InvertedIndexService</summary>
    public abstract partial class InvertedIndexServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> ClearIndices(global::XiaoyaStore.Service.ArgId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.Result> SaveIndices(global::XiaoyaStore.Service.ArgSaveIndices request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::XiaoyaStore.Service.ResultWithIndex> GetIndex(global::XiaoyaStore.Service.ArgIndexKey request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for InvertedIndexService</summary>
    public partial class InvertedIndexServiceClient : grpc::ClientBase<InvertedIndexServiceClient>
    {
      /// <summary>Creates a new client for InvertedIndexService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public InvertedIndexServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for InvertedIndexService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public InvertedIndexServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected InvertedIndexServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected InvertedIndexServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::XiaoyaStore.Service.Result ClearIndices(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ClearIndices(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result ClearIndices(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ClearIndices, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ClearIndicesAsync(global::XiaoyaStore.Service.ArgId request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ClearIndicesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> ClearIndicesAsync(global::XiaoyaStore.Service.ArgId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ClearIndices, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.Result SaveIndices(global::XiaoyaStore.Service.ArgSaveIndices request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SaveIndices(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.Result SaveIndices(global::XiaoyaStore.Service.ArgSaveIndices request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveIndices, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> SaveIndicesAsync(global::XiaoyaStore.Service.ArgSaveIndices request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SaveIndicesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.Result> SaveIndicesAsync(global::XiaoyaStore.Service.ArgSaveIndices request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveIndices, null, options, request);
      }
      public virtual global::XiaoyaStore.Service.ResultWithIndex GetIndex(global::XiaoyaStore.Service.ArgIndexKey request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetIndex(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::XiaoyaStore.Service.ResultWithIndex GetIndex(global::XiaoyaStore.Service.ArgIndexKey request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetIndex, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithIndex> GetIndexAsync(global::XiaoyaStore.Service.ArgIndexKey request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetIndexAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::XiaoyaStore.Service.ResultWithIndex> GetIndexAsync(global::XiaoyaStore.Service.ArgIndexKey request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetIndex, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override InvertedIndexServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new InvertedIndexServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(InvertedIndexServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ClearIndices, serviceImpl.ClearIndices)
          .AddMethod(__Method_SaveIndices, serviceImpl.SaveIndices)
          .AddMethod(__Method_GetIndex, serviceImpl.GetIndex).Build();
    }

  }
}
#endregion
