// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using XiaoyaStore.Data;
using XiaoyaStore.Data.Model;

namespace XiaoyaStore.Migrations
{
    [DbContext(typeof(XiaoyaSearchContext))]
    partial class XiaoyaSearchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("XiaoyaStore.Data.Model.IndexStat", b =>
                {
                    b.Property<int>("IndexStatId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("DocumentFrequency")
                        .IsConcurrencyToken();

                    b.Property<string>("Word")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("WordFrequency")
                        .IsConcurrencyToken();

                    b.HasKey("IndexStatId");

                    b.HasIndex("Word")
                        .IsUnique()
                        .HasFilter("[Word] IS NOT NULL");

                    b.HasIndex("WordFrequency");

                    b.ToTable("IndexStats");
                });

            modelBuilder.Entity("XiaoyaStore.Data.Model.InvertedIndex", b =>
                {
                    b.Property<int>("InvertedIndexId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OccurencesInLinks")
                        .IsConcurrencyToken();

                    b.Property<int>("OccurencesInTitle")
                        .IsConcurrencyToken();

                    b.Property<string>("Positions")
                        .IsConcurrencyToken();

                    b.Property<int>("UrlFileId")
                        .IsConcurrencyToken();

                    b.Property<double>("Weight")
                        .IsConcurrencyToken();

                    b.Property<string>("Word")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("WordFrequency")
                        .IsConcurrencyToken();

                    b.HasKey("InvertedIndexId");

                    b.HasIndex("UrlFileId");

                    b.HasIndex("Weight");

                    b.HasIndex("Word");

                    b.HasIndex("Word", "UrlFileId")
                        .IsUnique()
                        .HasFilter("[Word] IS NOT NULL");

                    b.HasIndex("Word", "Weight");

                    b.ToTable("InvertedIndices");
                });

            modelBuilder.Entity("XiaoyaStore.Data.Model.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.Property<string>("Url");

                    b.Property<int>("UrlFileId");

                    b.HasKey("LinkId");

                    b.HasIndex("Url");

                    b.HasIndex("UrlFileId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("XiaoyaStore.Data.Model.UrlFile", b =>
                {
                    b.Property<int>("UrlFileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Charset")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Content")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FileHash")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IndexStatus")
                        .IsConcurrencyToken();

                    b.Property<string>("MimeType")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PageRank");

                    b.Property<DateTime>("PublishDate")
                        .IsConcurrencyToken();

                    b.Property<string>("Title");

                    b.Property<double>("UpdateIntervalSeconds")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken();

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("UrlFileId");

                    b.HasIndex("FileHash");

                    b.HasIndex("FilePath")
                        .IsUnique()
                        .HasFilter("[FilePath] IS NOT NULL");

                    b.HasIndex("IndexStatus");

                    b.HasIndex("PageRank");

                    b.HasIndex("PublishDate");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasFilter("[Url] IS NOT NULL");

                    b.HasIndex("IndexStatus", "UpdatedAt");

                    b.ToTable("UrlFiles");
                });

            modelBuilder.Entity("XiaoyaStore.Data.Model.UrlFrontierItem", b =>
                {
                    b.Property<int>("UrlFrontierItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("FailedTimes")
                        .IsConcurrencyToken();

                    b.Property<string>("Host")
                        .IsConcurrencyToken();

                    b.Property<bool>("IsPopped")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("PlannedTime")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken();

                    b.Property<string>("Url")
                        .IsConcurrencyToken();

                    b.Property<int>("UrlDepth")
                        .IsConcurrencyToken();

                    b.HasKey("UrlFrontierItemId");

                    b.HasIndex("IsPopped");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasFilter("[Url] IS NOT NULL");

                    b.HasIndex("PlannedTime", "IsPopped");

                    b.ToTable("UrlFrontierItems");
                });

            modelBuilder.Entity("XiaoyaStore.Data.Model.UrlHostStat", b =>
                {
                    b.Property<int>("UrlHostStatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<string>("Host");

                    b.HasKey("UrlHostStatId");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasFilter("[Host] IS NOT NULL");

                    b.ToTable("UrlHostStats");
                });
#pragma warning restore 612, 618
        }
    }
}
